/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SkillFunOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addOperator"
      | "clearVerifiedClaim"
      | "operators"
      | "owner"
      | "removeOperator"
      | "renounceOwnership"
      | "setSkillNFT"
      | "setVerifiedClaims"
      | "skillNFT"
      | "transferOwnership"
      | "verifiedOwner"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OperatorAdded"
      | "OperatorRemoved"
      | "OwnershipTransferred"
      | "SkillNFTSet"
      | "VerifiedClaimCleared"
      | "VerifiedClaimsSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "clearVerifiedClaim",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "operators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setSkillNFT",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerifiedClaims",
    values: [BigNumberish[], AddressLike[]]
  ): string;
  encodeFunctionData(functionFragment: "skillNFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedOwner",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "clearVerifiedClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operators", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSkillNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerifiedClaims",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "skillNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedOwner",
    data: BytesLike
  ): Result;
}

export namespace OperatorAddedEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorRemovedEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SkillNFTSetEvent {
  export type InputTuple = [skillNFT: AddressLike];
  export type OutputTuple = [skillNFT: string];
  export interface OutputObject {
    skillNFT: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifiedClaimClearedEvent {
  export type InputTuple = [tokenId: BigNumberish];
  export type OutputTuple = [tokenId: bigint];
  export interface OutputObject {
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifiedClaimsSetEvent {
  export type InputTuple = [tokenIds: BigNumberish[], owners: AddressLike[]];
  export type OutputTuple = [tokenIds: bigint[], owners: string[]];
  export interface OutputObject {
    tokenIds: bigint[];
    owners: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SkillFunOracle extends BaseContract {
  connect(runner?: ContractRunner | null): SkillFunOracle;
  waitForDeployment(): Promise<this>;

  interface: SkillFunOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addOperator: TypedContractMethod<
    [operator: AddressLike],
    [void],
    "nonpayable"
  >;

  clearVerifiedClaim: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  operators: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeOperator: TypedContractMethod<
    [operator: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setSkillNFT: TypedContractMethod<
    [_skillNFT: AddressLike],
    [void],
    "nonpayable"
  >;

  setVerifiedClaims: TypedContractMethod<
    [tokenIds: BigNumberish[], owners: AddressLike[]],
    [void],
    "nonpayable"
  >;

  skillNFT: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifiedOwner: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addOperator"
  ): TypedContractMethod<[operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "clearVerifiedClaim"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "operators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeOperator"
  ): TypedContractMethod<[operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSkillNFT"
  ): TypedContractMethod<[_skillNFT: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerifiedClaims"
  ): TypedContractMethod<
    [tokenIds: BigNumberish[], owners: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "skillNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifiedOwner"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "OperatorAdded"
  ): TypedContractEvent<
    OperatorAddedEvent.InputTuple,
    OperatorAddedEvent.OutputTuple,
    OperatorAddedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorRemoved"
  ): TypedContractEvent<
    OperatorRemovedEvent.InputTuple,
    OperatorRemovedEvent.OutputTuple,
    OperatorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SkillNFTSet"
  ): TypedContractEvent<
    SkillNFTSetEvent.InputTuple,
    SkillNFTSetEvent.OutputTuple,
    SkillNFTSetEvent.OutputObject
  >;
  getEvent(
    key: "VerifiedClaimCleared"
  ): TypedContractEvent<
    VerifiedClaimClearedEvent.InputTuple,
    VerifiedClaimClearedEvent.OutputTuple,
    VerifiedClaimClearedEvent.OutputObject
  >;
  getEvent(
    key: "VerifiedClaimsSet"
  ): TypedContractEvent<
    VerifiedClaimsSetEvent.InputTuple,
    VerifiedClaimsSetEvent.OutputTuple,
    VerifiedClaimsSetEvent.OutputObject
  >;

  filters: {
    "OperatorAdded(address)": TypedContractEvent<
      OperatorAddedEvent.InputTuple,
      OperatorAddedEvent.OutputTuple,
      OperatorAddedEvent.OutputObject
    >;
    OperatorAdded: TypedContractEvent<
      OperatorAddedEvent.InputTuple,
      OperatorAddedEvent.OutputTuple,
      OperatorAddedEvent.OutputObject
    >;

    "OperatorRemoved(address)": TypedContractEvent<
      OperatorRemovedEvent.InputTuple,
      OperatorRemovedEvent.OutputTuple,
      OperatorRemovedEvent.OutputObject
    >;
    OperatorRemoved: TypedContractEvent<
      OperatorRemovedEvent.InputTuple,
      OperatorRemovedEvent.OutputTuple,
      OperatorRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SkillNFTSet(address)": TypedContractEvent<
      SkillNFTSetEvent.InputTuple,
      SkillNFTSetEvent.OutputTuple,
      SkillNFTSetEvent.OutputObject
    >;
    SkillNFTSet: TypedContractEvent<
      SkillNFTSetEvent.InputTuple,
      SkillNFTSetEvent.OutputTuple,
      SkillNFTSetEvent.OutputObject
    >;

    "VerifiedClaimCleared(uint256)": TypedContractEvent<
      VerifiedClaimClearedEvent.InputTuple,
      VerifiedClaimClearedEvent.OutputTuple,
      VerifiedClaimClearedEvent.OutputObject
    >;
    VerifiedClaimCleared: TypedContractEvent<
      VerifiedClaimClearedEvent.InputTuple,
      VerifiedClaimClearedEvent.OutputTuple,
      VerifiedClaimClearedEvent.OutputObject
    >;

    "VerifiedClaimsSet(uint256[],address[])": TypedContractEvent<
      VerifiedClaimsSetEvent.InputTuple,
      VerifiedClaimsSetEvent.OutputTuple,
      VerifiedClaimsSetEvent.OutputObject
    >;
    VerifiedClaimsSet: TypedContractEvent<
      VerifiedClaimsSetEvent.InputTuple,
      VerifiedClaimsSetEvent.OutputTuple,
      VerifiedClaimsSetEvent.OutputObject
    >;
  };
}
