/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type AccessProofStruct = {
  oldDataHash: BytesLike;
  newDataHash: BytesLike;
  nonce: BytesLike;
  encryptedPubKey: BytesLike;
  proof: BytesLike;
};

export type AccessProofStructOutput = [
  oldDataHash: string,
  newDataHash: string,
  nonce: string,
  encryptedPubKey: string,
  proof: string
] & {
  oldDataHash: string;
  newDataHash: string;
  nonce: string;
  encryptedPubKey: string;
  proof: string;
};

export type OwnershipProofStruct = {
  oracleType: BigNumberish;
  oldDataHash: BytesLike;
  newDataHash: BytesLike;
  sealedKey: BytesLike;
  encryptedPubKey: BytesLike;
  nonce: BytesLike;
  proof: BytesLike;
};

export type OwnershipProofStructOutput = [
  oracleType: bigint,
  oldDataHash: string,
  newDataHash: string,
  sealedKey: string,
  encryptedPubKey: string,
  nonce: string,
  proof: string
] & {
  oracleType: bigint;
  oldDataHash: string;
  newDataHash: string;
  sealedKey: string;
  encryptedPubKey: string;
  nonce: string;
  proof: string;
};

export type TransferValidityProofStruct = {
  accessProof: AccessProofStruct;
  ownershipProof: OwnershipProofStruct;
};

export type TransferValidityProofStructOutput = [
  accessProof: AccessProofStructOutput,
  ownershipProof: OwnershipProofStructOutput
] & {
  accessProof: AccessProofStructOutput;
  ownershipProof: OwnershipProofStructOutput;
};

export type TransferValidityProofOutputStruct = {
  oldDataHash: BytesLike;
  newDataHash: BytesLike;
  sealedKey: BytesLike;
  encryptedPubKey: BytesLike;
  wantedKey: BytesLike;
  accessAssistant: AddressLike;
  accessProofNonce: BytesLike;
  ownershipProofNonce: BytesLike;
};

export type TransferValidityProofOutputStructOutput = [
  oldDataHash: string,
  newDataHash: string,
  sealedKey: string,
  encryptedPubKey: string,
  wantedKey: string,
  accessAssistant: string,
  accessProofNonce: string,
  ownershipProofNonce: string
] & {
  oldDataHash: string;
  newDataHash: string;
  sealedKey: string;
  encryptedPubKey: string;
  wantedKey: string;
  accessAssistant: string;
  accessProofNonce: string;
  ownershipProofNonce: string;
};

export interface SkillFunVerifierStubInterface extends Interface {
  getFunction(nameOrSignature: "verifyTransferValidity"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "verifyTransferValidity",
    values: [TransferValidityProofStruct[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "verifyTransferValidity",
    data: BytesLike
  ): Result;
}

export interface SkillFunVerifierStub extends BaseContract {
  connect(runner?: ContractRunner | null): SkillFunVerifierStub;
  waitForDeployment(): Promise<this>;

  interface: SkillFunVerifierStubInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  verifyTransferValidity: TypedContractMethod<
    [_proofs: TransferValidityProofStruct[]],
    [TransferValidityProofOutputStructOutput[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "verifyTransferValidity"
  ): TypedContractMethod<
    [_proofs: TransferValidityProofStruct[]],
    [TransferValidityProofOutputStructOutput[]],
    "view"
  >;

  filters: {};
}
