/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SkillFunOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "clearVerifiedClaim"
      | "coldWallet"
      | "setSkillNFT"
      | "setVerifiedClaims"
      | "skillNFT"
      | "verifiedOwner"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "SkillNFTSet"
      | "VerifiedClaimCleared"
      | "VerifiedClaimsSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "clearVerifiedClaim",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "coldWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setSkillNFT",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerifiedClaims",
    values: [BigNumberish[], AddressLike[]]
  ): string;
  encodeFunctionData(functionFragment: "skillNFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifiedOwner",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "clearVerifiedClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "coldWallet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSkillNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerifiedClaims",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "skillNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifiedOwner",
    data: BytesLike
  ): Result;
}

export namespace SkillNFTSetEvent {
  export type InputTuple = [skillNFT: AddressLike];
  export type OutputTuple = [skillNFT: string];
  export interface OutputObject {
    skillNFT: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifiedClaimClearedEvent {
  export type InputTuple = [tokenId: BigNumberish];
  export type OutputTuple = [tokenId: bigint];
  export interface OutputObject {
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifiedClaimsSetEvent {
  export type InputTuple = [tokenIds: BigNumberish[], owners: AddressLike[]];
  export type OutputTuple = [tokenIds: bigint[], owners: string[]];
  export interface OutputObject {
    tokenIds: bigint[];
    owners: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SkillFunOracle extends BaseContract {
  connect(runner?: ContractRunner | null): SkillFunOracle;
  waitForDeployment(): Promise<this>;

  interface: SkillFunOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  clearVerifiedClaim: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  coldWallet: TypedContractMethod<[], [string], "view">;

  setSkillNFT: TypedContractMethod<
    [_skillNFT: AddressLike],
    [void],
    "nonpayable"
  >;

  setVerifiedClaims: TypedContractMethod<
    [tokenIds: BigNumberish[], owners: AddressLike[]],
    [void],
    "nonpayable"
  >;

  skillNFT: TypedContractMethod<[], [string], "view">;

  verifiedOwner: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "clearVerifiedClaim"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "coldWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setSkillNFT"
  ): TypedContractMethod<[_skillNFT: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerifiedClaims"
  ): TypedContractMethod<
    [tokenIds: BigNumberish[], owners: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "skillNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifiedOwner"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "SkillNFTSet"
  ): TypedContractEvent<
    SkillNFTSetEvent.InputTuple,
    SkillNFTSetEvent.OutputTuple,
    SkillNFTSetEvent.OutputObject
  >;
  getEvent(
    key: "VerifiedClaimCleared"
  ): TypedContractEvent<
    VerifiedClaimClearedEvent.InputTuple,
    VerifiedClaimClearedEvent.OutputTuple,
    VerifiedClaimClearedEvent.OutputObject
  >;
  getEvent(
    key: "VerifiedClaimsSet"
  ): TypedContractEvent<
    VerifiedClaimsSetEvent.InputTuple,
    VerifiedClaimsSetEvent.OutputTuple,
    VerifiedClaimsSetEvent.OutputObject
  >;

  filters: {
    "SkillNFTSet(address)": TypedContractEvent<
      SkillNFTSetEvent.InputTuple,
      SkillNFTSetEvent.OutputTuple,
      SkillNFTSetEvent.OutputObject
    >;
    SkillNFTSet: TypedContractEvent<
      SkillNFTSetEvent.InputTuple,
      SkillNFTSetEvent.OutputTuple,
      SkillNFTSetEvent.OutputObject
    >;

    "VerifiedClaimCleared(uint256)": TypedContractEvent<
      VerifiedClaimClearedEvent.InputTuple,
      VerifiedClaimClearedEvent.OutputTuple,
      VerifiedClaimClearedEvent.OutputObject
    >;
    VerifiedClaimCleared: TypedContractEvent<
      VerifiedClaimClearedEvent.InputTuple,
      VerifiedClaimClearedEvent.OutputTuple,
      VerifiedClaimClearedEvent.OutputObject
    >;

    "VerifiedClaimsSet(uint256[],address[])": TypedContractEvent<
      VerifiedClaimsSetEvent.InputTuple,
      VerifiedClaimsSetEvent.OutputTuple,
      VerifiedClaimsSetEvent.OutputObject
    >;
    VerifiedClaimsSet: TypedContractEvent<
      VerifiedClaimsSetEvent.InputTuple,
      VerifiedClaimsSetEvent.OutputTuple,
      VerifiedClaimsSetEvent.OutputObject
    >;
  };
}
