/**
 * @workspace/abi
 *
 * Centralised ABI + address exports for SkillFun contracts.
 *
 * Usage (frontend / backend):
 *   import { SkillNFT_ABI, SkillFunOracle_ABI, getAddresses } from '@workspace/abi'
 *
 * ABI files (*.abi.json) are generated by running:
 *   pnpm --filter @workspace/contracts run compile
 *   pnpm --filter @workspace/contracts run export-abi
 *
 * addresses.json is written by the deploy script automatically.
 */

// ---------------------------------------------------------------------------
// ABI imports
// These files are generated at compile time. Run `pnpm run compile` in
// packages/contracts first.
// ---------------------------------------------------------------------------

// eslint-disable-next-line @typescript-eslint/no-var-requires
export const SkillFunOracle_ABI = require("./SkillFunOracle.abi.json") as readonly object[];
// eslint-disable-next-line @typescript-eslint/no-var-requires
export const SkillNFT_ABI = require("./SkillNFT.abi.json") as readonly object[];

// ---------------------------------------------------------------------------
// Address registry
// ---------------------------------------------------------------------------

type ContractName = "SkillFunOracle" | "SkillNFT";
type AddressMap = Record<string, Record<ContractName, string>>;

// addresses.json is written by the deploy script.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const _addresses: AddressMap = (() => {
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    return require("./addresses.json");
  } catch {
    return {};
  }
})();

/**
 * Get contract addresses for a given chainId.
 * @param chainId  e.g. 16601 (0G testnet), 31337 (Hardhat local)
 */
export function getAddresses(chainId: number): Record<ContractName, string> {
  const entry = _addresses[String(chainId)];
  if (!entry) {
    throw new Error(
      `No contract addresses found for chainId ${chainId}. ` +
        "Run the deploy script first."
    );
  }
  return entry;
}

/**
 * All stored address entries, keyed by chainId string.
 */
export const allAddresses: AddressMap = _addresses;

// ---------------------------------------------------------------------------
// Chain config
// ---------------------------------------------------------------------------

export const ZEROG_TESTNET = {
  id: 16601,
  name: "0G Newton Testnet",
  nativeCurrency: { name: "0G", symbol: "0G", decimals: 18 },
  rpcUrls: {
    default: { http: ["https://evmrpc-testnet.0g.ai"] },
  },
  blockExplorers: {
    default: {
      name: "0G Scan",
      url: "https://chainscan-newton.0g.ai",
    },
  },
} as const;
