/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC7857DataVerifier,
  IERC7857DataVerifierInterface,
} from "../../../contracts/interfaces/IERC7857DataVerifier";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "bytes32",
                name: "oldDataHash",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "newDataHash",
                type: "bytes32",
              },
              {
                internalType: "bytes",
                name: "nonce",
                type: "bytes",
              },
              {
                internalType: "bytes",
                name: "encryptedPubKey",
                type: "bytes",
              },
              {
                internalType: "bytes",
                name: "proof",
                type: "bytes",
              },
            ],
            internalType: "struct AccessProof",
            name: "accessProof",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "enum OracleType",
                name: "oracleType",
                type: "uint8",
              },
              {
                internalType: "bytes32",
                name: "oldDataHash",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "newDataHash",
                type: "bytes32",
              },
              {
                internalType: "bytes",
                name: "sealedKey",
                type: "bytes",
              },
              {
                internalType: "bytes",
                name: "encryptedPubKey",
                type: "bytes",
              },
              {
                internalType: "bytes",
                name: "nonce",
                type: "bytes",
              },
              {
                internalType: "bytes",
                name: "proof",
                type: "bytes",
              },
            ],
            internalType: "struct OwnershipProof",
            name: "ownershipProof",
            type: "tuple",
          },
        ],
        internalType: "struct TransferValidityProof[]",
        name: "_proofs",
        type: "tuple[]",
      },
    ],
    name: "verifyTransferValidity",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "oldDataHash",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "newDataHash",
            type: "bytes32",
          },
          {
            internalType: "bytes",
            name: "sealedKey",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "encryptedPubKey",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "wantedKey",
            type: "bytes",
          },
          {
            internalType: "address",
            name: "accessAssistant",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "accessProofNonce",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "ownershipProofNonce",
            type: "bytes",
          },
        ],
        internalType: "struct TransferValidityProofOutput[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC7857DataVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IERC7857DataVerifierInterface {
    return new Interface(_abi) as IERC7857DataVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC7857DataVerifier {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IERC7857DataVerifier;
  }
}
