/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC7857Metadata,
  IERC7857MetadataInterface,
} from "../../../contracts/interfaces/IERC7857Metadata";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "intelligentDataOf",
    outputs: [
      {
        components: [
          {
            internalType: "string",
            name: "dataDescription",
            type: "string",
          },
          {
            internalType: "bytes32",
            name: "dataHash",
            type: "bytes32",
          },
        ],
        internalType: "struct IntelligentData[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IERC7857Metadata__factory {
  static readonly abi = _abi;
  static createInterface(): IERC7857MetadataInterface {
    return new Interface(_abi) as IERC7857MetadataInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC7857Metadata {
    return new Contract(address, _abi, runner) as unknown as IERC7857Metadata;
  }
}
