/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  SkillFunVerifierStub,
  SkillFunVerifierStubInterface,
} from "../../contracts/SkillFunVerifierStub";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "bytes32",
                name: "oldDataHash",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "newDataHash",
                type: "bytes32",
              },
              {
                internalType: "bytes",
                name: "nonce",
                type: "bytes",
              },
              {
                internalType: "bytes",
                name: "encryptedPubKey",
                type: "bytes",
              },
              {
                internalType: "bytes",
                name: "proof",
                type: "bytes",
              },
            ],
            internalType: "struct AccessProof",
            name: "accessProof",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "enum OracleType",
                name: "oracleType",
                type: "uint8",
              },
              {
                internalType: "bytes32",
                name: "oldDataHash",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "newDataHash",
                type: "bytes32",
              },
              {
                internalType: "bytes",
                name: "sealedKey",
                type: "bytes",
              },
              {
                internalType: "bytes",
                name: "encryptedPubKey",
                type: "bytes",
              },
              {
                internalType: "bytes",
                name: "nonce",
                type: "bytes",
              },
              {
                internalType: "bytes",
                name: "proof",
                type: "bytes",
              },
            ],
            internalType: "struct OwnershipProof",
            name: "ownershipProof",
            type: "tuple",
          },
        ],
        internalType: "struct TransferValidityProof[]",
        name: "_proofs",
        type: "tuple[]",
      },
    ],
    name: "verifyTransferValidity",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "oldDataHash",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "newDataHash",
            type: "bytes32",
          },
          {
            internalType: "bytes",
            name: "sealedKey",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "encryptedPubKey",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "wantedKey",
            type: "bytes",
          },
          {
            internalType: "address",
            name: "accessAssistant",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "accessProofNonce",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "ownershipProofNonce",
            type: "bytes",
          },
        ],
        internalType: "struct TransferValidityProofOutput[]",
        name: "outputs",
        type: "tuple[]",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561000f575f80fd5b506102ef8061001d5f395ff3fe608060405234801561000f575f80fd5b5060043610610029575f3560e01c8063df6301161461002d575b5f80fd5b61004061003b3660046100e9565b610056565b60405161004d919061019b565b60405180910390f35b60608167ffffffffffffffff811115610071576100716102a5565b6040519080825280602002602001820160405280156100e157816020015b60408051610100810182525f8082526020820181905260609282018390528282018390526080820183905260a082015260c0810182905260e081019190915281526020019060019003908161008f5790505b509392505050565b5f80602083850312156100fa575f80fd5b823567ffffffffffffffff80821115610111575f80fd5b818501915085601f830112610124575f80fd5b813581811115610132575f80fd5b8660208260051b8501011115610146575f80fd5b60209290920196919550909350505050565b5f81518084525f5b8181101561017c57602081850181015186830182015201610160565b505f602082860101526020601f19601f83011685010191505092915050565b5f60208083018184528085518083526040925060408601915060408160051b8701018488015f5b8381101561029757603f1989840301855281516101008151855288820151898601528782015181898701526101f982870182610158565b915050606080830151868303828801526102138382610158565b925050506080808301518683038288015261022e8382610158565b9250505060a08083015161024c828801826001600160a01b03169052565b505060c080830151868303828801526102658382610158565b9250505060e080830151925085820381870152506102838183610158565b9689019694505050908601906001016101c2565b509098975050505050505050565b634e487b7160e01b5f52604160045260245ffdfea264697066735822122076f3ebca4a9f0e479c07873945519eeb41b713d360690841b1e58afd72ae7ec764736f6c63430008180033";

type SkillFunVerifierStubConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SkillFunVerifierStubConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SkillFunVerifierStub__factory extends ContractFactory {
  constructor(...args: SkillFunVerifierStubConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SkillFunVerifierStub & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): SkillFunVerifierStub__factory {
    return super.connect(runner) as SkillFunVerifierStub__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SkillFunVerifierStubInterface {
    return new Interface(_abi) as SkillFunVerifierStubInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SkillFunVerifierStub {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as SkillFunVerifierStub;
  }
}
